apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gateway-influxdb
  name: gateway-influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi