apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gateway-prometheus
  name: gateway-prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi