version: '3'

services:
  zookeeper:
    image: zookeeper:3.5.7
    restart: always
    ports:
      - 2181:2181
  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.100.21
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    depends_on:
      - zookeeper
    image: kafkamanager/kafka-manager:3.0.0.4
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181