{
 "title": "Gateway",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "jvm_memory_used_bytes" },
   { "name": "granularity", "label": "Granularity", "query": "1m,30s,5m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Outbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Send Rate",
   "type": "graph",
   "description": "Rate of outbound events sent to the user",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_outbound_sent_total[$granularity])) by (app, pod, instance)",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "Received Rate",
   "type": "graph",
   "description": "Rate of received outbound events",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_outbound_received_total{instance=~\"$instance\"}[$granularity])) by (app, pod, instance)",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "Avg Sent by Connection",
   "type": "graph",
   "description": "Avg events sent by connection",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "ops", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "avg(rate(gateway_outbound_sent_total{instance=~\"$instance\"}[$granularity])) by (app, pod, instance, connection)",
     "legendFormat": "Events"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active Connections",
   "type": "gauge",
   "description": "Active Web Socket connections",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gateway_active_connections{instance=~\"$instance\"}) by (app, instance)",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Active connections by instance",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "sum(gateway_active_connections{instance=~\"$instance\"}) by (app, instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_connections_errors_total{instance=~\"$instance\"}[$granularity])) by (app, pod, instance)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Error rate by status",
   "type": "graph",
   "description": "Top errors count by response status",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_connections_errors_total{instance=~\"$instance\"}[$granularity])) by (app, pod, instance, response_status)",
     "legendFormat": "Status - {{response_status}}"
    }
   ]
  },
  { "title": "Inbound", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Inbound Rate",
   "type": "graph",
   "description": "Rate of inbound events across all endpoints",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ops", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_inbound_received_total{instance=~\"$instance\"}[$granularity])) by (app, pod, instance)",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "Top endpoints",
   "type": "graph",
   "description": "Top endpoints by number of incoming inbound events",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 28 },
   "yaxes": [
    { "format": "Events" }
   ],
   "targets": [
    {
     "expr": "sum(topk(10, gateway_inbound_received_total{instance=~\"$instance\"})) by (app, endpoint_path)",
     "legendFormat": "Endpoint - {{endpoint_path}}"
    }
   ]
  },
  {
   "title": "Events per backend type",
   "type": "graph",
   "description": "Count of inbound events sent per backend type",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_inbound_backends_seconds_count[$granularity])) by (app, backend_type)",
     "legendFormat": "Events - {{backend_type}}"
    }
   ]
  },
  {
   "title": "Inbound Duration",
   "type": "graph",
   "description": "Duration for processing inbound events",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gateway_inbound_seconds_bucket{instance=~\"$instance\"}[$granularity])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gateway_inbound_seconds_bucket{instance=~\"$instance\"}[$granularity])) by (le))",
     "legendFormat": "95th"
    }
   ]
  },
  {
   "title": "Backend Duration",
   "type": "graph",
   "description": "Duration for sending inbound events to backends",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gateway_inbound_backends_seconds_bucket{instance=~\"$instance\"}[$granularity])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gateway_inbound_backends_seconds_bucket{instance=~\"$instance\"}[$granularity])) by (le))",
     "legendFormat": "95th"
    }
   ]
  },
  {
   "title": "Top backends",
   "type": "graph",
   "description": "Top backends by events they got",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "sum(topk(20, gateway_inbound_backends_seconds_count)) by(app, backend_destination)",
     "legendFormat": "Events - {{backend_destination}}"
    }
   ]
  }
 ]
}