apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-swagger-ui-deployment
  labels:
    app: swagger-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: ws-gateway
          image: ws-gateway/swagger-ui:1.0.1-alpha
          imagePullPolicy: Never
          resources:
            requests:
              memory: "32Mi"
              cpu: "150m"
            limits:
              memory: "128Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /swagger
              port: app
            periodSeconds: 5
          ports:
            - name: app
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-swagger-ui-service
spec:
  selector:
    app: swagger-ui
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
