spring:
  sleuth:
    messaging:
      kafka:
        enabled: false
        streams:
          enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "env,health,metrics,prometheus"
      base-path: /
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 0.95, 0.99
            percentiles-histogram: true
    export:
      prometheus:
        enabled: true

gateway:
  kubernetes:
    namespace: "gateway"
    serviceName: "gateway"
  pubsub:
    ignite: false
    hazelcast: true
    mocked: false
  persistence:
    mocked: true