### list all
GET http://localhost:8080/api/internal/endpoints

### Create
POST http://localhost:8080/api/internal/endpoints
Content-Type: application/json

{
  "path": "/my-ws-endpoint",
  "authentication": {
    "mode": "basic",
    "username": "basic_user",
    "password":  "strongPassword"
  },
  "routes": [
    {
      "type": "connect",
      "name": "Connect",
      "backends": [
        {
          "type": "http",
          "destination": "http://service.1.example.com/connect",
          "timeoutInMillis": 300,
          "additionalHeaders": {
            "X-Debug-Id": "id"
          }
        },
        {
          "type": "kafka",
          "topic": "service.2.connect.topic"
        }
      ]
    },
    {
      "type": "disconnect",
      "name": "Disconnect",
      "backends": [
        {
          "type": "http",
          "destination": "http://service.1.example.com/disconnect",
          "timeoutInMillis": 300,
          "additionalHeaders": {
            "X-Debug-Id": "id"
          }
        },
        {
          "type": "kafka",
          "topic": "service.2.diconnect.topic"
        }
      ]
    },
    {
      "type": "default",
      "name": "Default",
      "backends": [
        {
          "type": "http",
          "destination": "http://service.1.example.com/default",
          "timeoutInMillis": 300
        }
      ]
    }
  ]
}

###


