apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-grafana
  labels:
    app: gateway-grafana
    version: 1.0.0-alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-grafana
  template:
    metadata:
      labels:
        app: gateway-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:7.0.3-ubuntu
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - name: default
              containerPort: 3000
          env:
#            - GF_SECURITY_ADMIN_USER
            - name: GF_INSTALL_PLUGINS
              valueFrom:
                configMapKeyRef:
                  name: grafana
                  key: plugins