apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
        - name: gateway
          image: ws-gateway:1.0.1-alpha
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              path: /health/ready
              port: management
            initialDelaySeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/alive
              port: management
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
          env:
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: cors.allowedOrigins
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-secrets
                  key: appSecret
          ports:
            - name: application
              containerPort: 9000
            - name: management
              containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-app
  ports:
    - port: 9000
      targetPort: 9000
  type: LoadBalancer
