apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-app
  ports:
    - name: app
      port: 9000
      targetPort: 9000
    - name: management
      port: 9001
      targetPort: 9001
  type: LoadBalancer
