name: Coding Style

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run Checkstyle
      run: mvn checkstyle:checkstyle-aggregate
    - name: misspell
      uses: reviewdog/action-misspell@v1
      with:
        github_token: ${{ secrets.CI_CD_GITHUB_TOKEN }}
        locale: "US"
        level: info
        reporter: github-pr-review
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.10.2
    - name: Run reviewdog check
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.CI_CD_GITHUB_TOKEN }}
      run: |
        cat target/checkstyle-result.xml | reviewdog -f=checkstyle -diff="git diff master" -reporter=github-pr-check

