name: Master code coverage

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - 'tools/**'
      - 'deployment/**'
jobs:
  CodeCoverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run All Tests
        run: mvn --no-transfer-progress clean test
      - name: Run Tests for Apache Ignite integration
        run: mvn --no-transfer-progress test -Dgroups=pubsub -Dspring.profiles.active=ignite,tests
      - uses: codecov/codecov-action@v1
        name: Upload code coverage report
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./ws-gateway-api/target/site/jacoco/jacoco.xml,./ws-gateway-application/target/site/jacoco/jacoco.xml,./ws-gateway-domain/target/site/jacoco/jacoco.xml,./ws-gateway-infrastructure/target/site/jacoco/jacoco.xml,./ws-gateway-functional-tests/target/site/jacoco/jacoco.xml
          fail_ci_if_error: false