name: Tests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run All Tests
      run: mvn --no-transfer-progress clean verify
    - name: Run Tests for Apache Ignite integration
      run: mvn --no-transfer-progress clean test -Dgroups=pubsub -Dspring.profiles.active=ignite,tests